version: '3.6'

services:
  db:
    image: mariadb:latest
    restart: always
    environment:
      MARIADB_USER: rnconfig
      MARIADB_PASSWORD: password1234
      MARIADB_ROOT_PASSWORD: password1234
      MARIADB_DATABASE: RnConfig
    
    volumes:
      - ./init:/docker-entrypoint-initdb.d

    ports:
      - 3306:3306
